// generated via source generation from xbim.xids.generator
namespace Xbim.InformationSpecifications.Helpers
{
	public partial class SchemaInfo
	{
		static partial void GetClassesIFC2x3()
		{
			schemaIFC2x3 = new SchemaInfo();
			schemaIFC2x3.Add(new ClassInfo("IfcObject", "IfcObjectDefinition", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcProduct", "IfcObject", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralActivity", "IfcProduct", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralAction", "IfcStructuralActivity", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralLinearAction", "IfcStructuralAction", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralLinearActionVarying", "IfcStructuralLinearAction", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralPlanarAction", "IfcStructuralAction", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralPlanarActionVarying", "IfcStructuralPlanarAction", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralPointAction", "IfcStructuralAction", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralReaction", "IfcStructuralActivity", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralPointReaction", "IfcStructuralReaction", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralItem", "IfcProduct", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralConnection", "IfcStructuralItem", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralCurveConnection", "IfcStructuralConnection", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralPointConnection", "IfcStructuralConnection", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralSurfaceConnection", "IfcStructuralConnection", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralMember", "IfcStructuralItem", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralCurveMember", "IfcStructuralMember", ClassType.Concrete, new[] { "RIGID_JOINED_MEMBER", "PIN_JOINED_MEMBER", "CABLE", "TENSION_MEMBER", "COMPRESSION_MEMBER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralCurveMemberVarying", "IfcStructuralCurveMember", ClassType.Concrete, new[] { "RIGID_JOINED_MEMBER", "PIN_JOINED_MEMBER", "CABLE", "TENSION_MEMBER", "COMPRESSION_MEMBER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralSurfaceMember", "IfcStructuralMember", ClassType.Concrete, new[] { "BENDING_ELEMENT", "MEMBRANE_ELEMENT", "SHELL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralSurfaceMemberVarying", "IfcStructuralSurfaceMember", ClassType.Concrete, new[] { "BENDING_ELEMENT", "MEMBRANE_ELEMENT", "SHELL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElement", "IfcProduct", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionFlowElement", "IfcDistributionElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionChamberElement", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcEnergyConversionDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowController", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricDistributionPoint", "IfcFlowController", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowFitting", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowMovingDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowSegment", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowStorageDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowTerminal", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowTreatmentDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionControlElement", "IfcDistributionElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcElementComponent", "IfcElement", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDiscreteAccessory", "IfcElementComponent", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFastener", "IfcElementComponent", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcMechanicalFastener", "IfcFastener", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFeatureElement", "IfcElement", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFeatureElementSubtraction", "IfcFeatureElement", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcEdgeFeature", "IfcFeatureElementSubtraction", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcChamferEdgeFeature", "IfcEdgeFeature", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcRoundedEdgeFeature", "IfcEdgeFeature", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcOpeningElement", "IfcFeatureElementSubtraction", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFeatureElementAddition", "IfcFeatureElement", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcProjectionElement", "IfcFeatureElementAddition", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBuildingElement", "IfcElement", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBuildingElementComponent", "IfcBuildingElement", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBuildingElementPart", "IfcBuildingElementComponent", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcReinforcingElement", "IfcBuildingElementComponent", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcReinforcingBar", "IfcReinforcingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcReinforcingMesh", "IfcReinforcingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcTendon", "IfcReinforcingElement", ClassType.Concrete, new[] { "STRAND", "WIRE", "BAR", "COATED", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcTendonAnchor", "IfcReinforcingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFooting", "IfcBuildingElement", ClassType.Concrete, new[] { "FOOTING_BEAM", "PAD_FOOTING", "PILE_CAP", "STRIP_FOOTING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcPile", "IfcBuildingElement", ClassType.Concrete, new[] { "COHESION", "FRICTION", "SUPPORT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcBeam", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcColumn", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcCurtainWall", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDoor", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcMember", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcPlate", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcRailing", "IfcBuildingElement", ClassType.Concrete, new[] { "HANDRAIL", "GUARDRAIL", "BALUSTRADE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcRamp", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcRampFlight", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcRoof", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSlab", "IfcBuildingElement", ClassType.Concrete, new[] { "FLOOR", "ROOF", "LANDING", "BASESLAB", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcStair", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStairFlight", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcWall", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcWallStandardCase", "IfcWall", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcWindow", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBuildingElementProxy", "IfcBuildingElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcCovering", "IfcBuildingElement", ClassType.Concrete, new[] { "CEILING", "FLOORING", "CLADDING", "ROOFING", "INSULATION", "MEMBRANE", "SLEEVING", "WRAPPING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElementAssembly", "IfcElement", ClassType.Concrete, new[] { "ACCESSORY_ASSEMBLY", "ARCH", "BEAM_GRID", "BRACED_FRAME", "GIRDER", "REINFORCEMENT_UNIT", "RIGID_FRAME", "SLAB_FIELD", "TRUSS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFurnishingElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcTransportElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcVirtualElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricalElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcEquipmentElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcPort", "IfcProduct", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionPort", "IfcPort", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcAnnotation", "IfcProduct", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSpatialStructureElement", "IfcProduct", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBuilding", "IfcSpatialStructureElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBuildingStorey", "IfcSpatialStructureElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSite", "IfcSpatialStructureElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSpace", "IfcSpatialStructureElement", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcGrid", "IfcProduct", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcProxy", "IfcProduct", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcGroup", "IfcObject", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSystem", "IfcGroup", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralAnalysisModel", "IfcSystem", ClassType.Concrete, new[] { "IN_PLANE_LOADING_2D", "OUT_PLANE_LOADING_2D", "LOADING_3D", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricalCircuit", "IfcSystem", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralLoadGroup", "IfcGroup", ClassType.Concrete, new[] { "LOAD_GROUP", "LOAD_CASE", "LOAD_COMBINATION_GROUP", "LOAD_COMBINATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcStructuralResultGroup", "IfcGroup", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcAsset", "IfcGroup", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcInventory", "IfcGroup", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcZone", "IfcGroup", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcCondition", "IfcGroup", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcProcess", "IfcObject", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcProcedure", "IfcProcess", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcTask", "IfcProcess", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcMove", "IfcTask", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcOrderAction", "IfcTask", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcControl", "IfcObject", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcWorkControl", "IfcControl", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcWorkPlan", "IfcWorkControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcWorkSchedule", "IfcWorkControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcScheduleTimeControl", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcCostItem", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcCostSchedule", "IfcControl", ClassType.Concrete, new[] { "BUDGET", "COSTPLAN", "ESTIMATE", "TENDER", "PRICEDBILLOFQUANTITIES", "UNPRICEDBILLOFQUANTITIES", "SCHEDULEOFRATES", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcProjectOrder", "IfcControl", ClassType.Concrete, new[] { "CHANGEORDER", "MAINTENANCEWORKORDER", "MOVEORDER", "PURCHASEORDER", "WORKORDER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcProjectOrderRecord", "IfcControl", ClassType.Concrete, new[] { "CHANGE", "MAINTENANCE", "MOVE", "PURCHASE", "WORK", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcServiceLife", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcActionRequest", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcConditionCriterion", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcEquipmentStandard", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFurnitureStandard", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcPermit", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcPerformanceHistory", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcTimeSeriesSchedule", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSpaceProgram", "IfcControl", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcActor", "IfcObject", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcOccupant", "IfcActor", ClassType.Concrete, new[] { "ASSIGNEE", "ASSIGNOR", "LESSEE", "LESSOR", "LETTINGAGENT", "OWNER", "TENANT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcProject", "IfcObject", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcResource", "IfcObject", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcConstructionResource", "IfcResource", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcConstructionEquipmentResource", "IfcConstructionResource", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcConstructionMaterialResource", "IfcConstructionResource", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcConstructionProductResource", "IfcConstructionResource", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcCrewResource", "IfcConstructionResource", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcLaborResource", "IfcConstructionResource", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSubContractResource", "IfcConstructionResource", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcTypeProduct", "IfcTypeObject", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcElementType", "IfcTypeProduct", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionElementType", "IfcElementType", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionFlowElementType", "IfcDistributionElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowTerminalType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFireSuppressionTerminalType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "BREECHINGINLET", "FIREHYDRANT", "HOSEREEL", "SPRINKLER", "SPRINKLERDEFLECTOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcSanitaryTerminalType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "BATH", "BIDET", "CISTERN", "SHOWER", "SINK", "SANITARYFOUNTAIN", "TOILETPAN", "URINAL", "WASHHANDBASIN", "WCSEAT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcStackTerminalType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "BIRDCAGE", "COWL", "RAINWATERHOPPER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcWasteTerminalType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "FLOORTRAP", "FLOORWASTE", "GULLYSUMP", "GULLYTRAP", "GREASEINTERCEPTOR", "OILINTERCEPTOR", "PETROLINTERCEPTOR", "ROOFDRAIN", "WASTEDISPOSALUNIT", "WASTETRAP", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcAirTerminalType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "GRILLE", "REGISTER", "DIFFUSER", "EYEBALL", "IRIS", "LINEARGRILLE", "LINEARDIFFUSER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcGasTerminalType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "GASAPPLIANCE", "GASBOOSTER", "GASBURNER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricApplianceType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "COMPUTER", "DIRECTWATERHEATER", "DISHWASHER", "ELECTRICCOOKER", "ELECTRICHEATER", "FACSIMILE", "FREESTANDINGFAN", "FREEZER", "FRIDGE_FREEZER", "HANDDRYER", "INDIRECTWATERHEATER", "MICROWAVE", "PHOTOCOPIER", "PRINTER", "REFRIGERATOR", "RADIANTHEATER", "SCANNER", "TELEPHONE", "TUMBLEDRYER", "TV", "VENDINGMACHINE", "WASHINGMACHINE", "WATERHEATER", "WATERCOOLER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricHeaterType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "ELECTRICPOINTHEATER", "ELECTRICCABLEHEATER", "ELECTRICMATHEATER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcLampType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "COMPACTFLUORESCENT", "FLUORESCENT", "HIGHPRESSUREMERCURY", "HIGHPRESSURESODIUM", "METALHALIDE", "TUNGSTENFILAMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcLightFixtureType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "POINTSOURCE", "DIRECTIONSOURCE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcOutletType", "IfcFlowTerminalType", ClassType.Concrete, new[] { "AUDIOVISUALOUTLET", "COMMUNICATIONSOUTLET", "POWEROUTLET", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionChamberElementType", "IfcDistributionFlowElementType", ClassType.Concrete, new[] { "FORMEDDUCT", "INSPECTIONCHAMBER", "INSPECTIONPIT", "MANHOLE", "METERCHAMBER", "SUMP", "TRENCH", "VALVECHAMBER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcEnergyConversionDeviceType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcAirToAirHeatRecoveryType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "FIXEDPLATECOUNTERFLOWEXCHANGER", "FIXEDPLATECROSSFLOWEXCHANGER", "FIXEDPLATEPARALLELFLOWEXCHANGER", "ROTARYWHEEL", "RUNAROUNDCOILLOOP", "HEATPIPE", "TWINTOWERENTHALPYRECOVERYLOOPS", "THERMOSIPHONSEALEDTUBEHEATEXCHANGERS", "THERMOSIPHONCOILTYPEHEATEXCHANGERS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcBoilerType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "WATER", "STEAM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcChillerType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "AIRCOOLED", "WATERCOOLED", "HEATRECOVERY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCoilType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "DXCOOLINGCOIL", "WATERCOOLINGCOIL", "STEAMHEATINGCOIL", "WATERHEATINGCOIL", "ELECTRICHEATINGCOIL", "GASHEATINGCOIL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCondenserType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "WATERCOOLEDSHELLTUBE", "WATERCOOLEDSHELLCOIL", "WATERCOOLEDTUBEINTUBE", "WATERCOOLEDBRAZEDPLATE", "AIRCOOLED", "EVAPORATIVECOOLED", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCooledBeamType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "ACTIVE", "PASSIVE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCoolingTowerType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "NATURALDRAFT", "MECHANICALINDUCEDDRAFT", "MECHANICALFORCEDDRAFT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcEvaporativeCoolerType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER", "DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER", "DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER", "DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER", "DIRECTEVAPORATIVEAIRWASHER", "INDIRECTEVAPORATIVEPACKAGEAIRCOOLER", "INDIRECTEVAPORATIVEWETCOIL", "INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER", "INDIRECTDIRECTCOMBINATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcEvaporatorType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "DIRECTEXPANSIONSHELLANDTUBE", "DIRECTEXPANSIONTUBEINTUBE", "DIRECTEXPANSIONBRAZEDPLATE", "FLOODEDSHELLANDTUBE", "SHELLANDCOIL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcHeatExchangerType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "PLATE", "SHELLANDTUBE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcHumidifierType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "STEAMINJECTION", "ADIABATICAIRWASHER", "ADIABATICPAN", "ADIABATICWETTEDELEMENT", "ADIABATICATOMIZING", "ADIABATICULTRASONIC", "ADIABATICRIGIDMEDIA", "ADIABATICCOMPRESSEDAIRNOZZLE", "ASSISTEDELECTRIC", "ASSISTEDNATURALGAS", "ASSISTEDPROPANE", "ASSISTEDBUTANE", "ASSISTEDSTEAM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcSpaceHeaterType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "SECTIONALRADIATOR", "PANELRADIATOR", "TUBULARRADIATOR", "CONVECTOR", "BASEBOARDHEATER", "FINNEDTUBEUNIT", "UNITHEATER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcTubeBundleType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "FINNED", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcUnitaryEquipmentType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "AIRHANDLER", "AIRCONDITIONINGUNIT", "SPLITSYSTEM", "ROOFTOPUNIT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricGeneratorType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricMotorType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "DC", "INDUCTION", "POLYPHASE", "RELUCTANCESYNCHRONOUS", "SYNCHRONOUS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcMotorConnectionType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "BELTDRIVE", "COUPLING", "DIRECTDRIVE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcTransformerType", "IfcEnergyConversionDeviceType", ClassType.Concrete, new[] { "CURRENT", "FREQUENCY", "VOLTAGE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowControllerType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcAirTerminalBoxType", "IfcFlowControllerType", ClassType.Concrete, new[] { "CONSTANTFLOW", "VARIABLEFLOWPRESSUREDEPENDANT", "VARIABLEFLOWPRESSUREINDEPENDANT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcDamperType", "IfcFlowControllerType", ClassType.Concrete, new[] { "CONTROLDAMPER", "FIREDAMPER", "SMOKEDAMPER", "FIRESMOKEDAMPER", "BACKDRAFTDAMPER", "RELIEFDAMPER", "BLASTDAMPER", "GRAVITYDAMPER", "GRAVITYRELIEFDAMPER", "BALANCINGDAMPER", "FUMEHOODEXHAUST", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowMeterType", "IfcFlowControllerType", ClassType.Concrete, new[] { "ELECTRICMETER", "ENERGYMETER", "FLOWMETER", "GASMETER", "OILMETER", "WATERMETER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcValveType", "IfcFlowControllerType", ClassType.Concrete, new[] { "AIRRELEASE", "ANTIVACUUM", "CHANGEOVER", "CHECK", "COMMISSIONING", "DIVERTING", "DRAWOFFCOCK", "DOUBLECHECK", "DOUBLEREGULATING", "FAUCET", "FLUSHING", "GASCOCK", "GASTAP", "ISOLATING", "MIXING", "PRESSUREREDUCING", "PRESSURERELIEF", "REGULATING", "SAFETYCUTOFF", "STEAMTRAP", "STOPCOCK", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricTimeControlType", "IfcFlowControllerType", ClassType.Concrete, new[] { "TIMECLOCK", "TIMEDELAY", "RELAY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcProtectiveDeviceType", "IfcFlowControllerType", ClassType.Concrete, new[] { "FUSEDISCONNECTOR", "CIRCUITBREAKER", "EARTHFAILUREDEVICE", "RESIDUALCURRENTCIRCUITBREAKER", "RESIDUALCURRENTSWITCH", "VARISTOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcSwitchingDeviceType", "IfcFlowControllerType", ClassType.Concrete, new[] { "CONTACTOR", "EMERGENCYSTOP", "STARTER", "SWITCHDISCONNECTOR", "TOGGLESWITCH", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowFittingType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDuctFittingType", "IfcFlowFittingType", ClassType.Concrete, new[] { "BEND", "CONNECTOR", "ENTRY", "EXIT", "JUNCTION", "OBSTRUCTION", "TRANSITION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcPipeFittingType", "IfcFlowFittingType", ClassType.Concrete, new[] { "BEND", "CONNECTOR", "ENTRY", "EXIT", "JUNCTION", "OBSTRUCTION", "TRANSITION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCableCarrierFittingType", "IfcFlowFittingType", ClassType.Concrete, new[] { "BEND", "CROSS", "REDUCER", "TEE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcJunctionBoxType", "IfcFlowFittingType", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowMovingDeviceType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcCompressorType", "IfcFlowMovingDeviceType", ClassType.Concrete, new[] { "DYNAMIC", "RECIPROCATING", "ROTARY", "SCROLL", "TROCHOIDAL", "SINGLESTAGE", "BOOSTER", "OPENTYPE", "HERMETIC", "SEMIHERMETIC", "WELDEDSHELLHERMETIC", "ROLLINGPISTON", "ROTARYVANE", "SINGLESCREW", "TWINSCREW", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFanType", "IfcFlowMovingDeviceType", ClassType.Concrete, new[] { "CENTRIFUGALFORWARDCURVED", "CENTRIFUGALRADIAL", "CENTRIFUGALBACKWARDINCLINEDCURVED", "CENTRIFUGALAIRFOIL", "TUBEAXIAL", "VANEAXIAL", "PROPELLORAXIAL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcPumpType", "IfcFlowMovingDeviceType", ClassType.Concrete, new[] { "CIRCULATOR", "ENDSUCTION", "SPLITCASE", "VERTICALINLINE", "VERTICALTURBINE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowSegmentType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDuctSegmentType", "IfcFlowSegmentType", ClassType.Concrete, new[] { "RIGIDSEGMENT", "FLEXIBLESEGMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcPipeSegmentType", "IfcFlowSegmentType", ClassType.Concrete, new[] { "FLEXIBLESEGMENT", "RIGIDSEGMENT", "GUTTER", "SPOOL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCableCarrierSegmentType", "IfcFlowSegmentType", ClassType.Concrete, new[] { "CABLELADDERSEGMENT", "CABLETRAYSEGMENT", "CABLETRUNKINGSEGMENT", "CONDUITSEGMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCableSegmentType", "IfcFlowSegmentType", ClassType.Concrete, new[] { "CABLESEGMENT", "CONDUCTORSEGMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowStorageDeviceType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcTankType", "IfcFlowStorageDeviceType", ClassType.Concrete, new[] { "PREFORMED", "SECTIONAL", "EXPANSION", "PRESSUREVESSEL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElectricFlowStorageDeviceType", "IfcFlowStorageDeviceType", ClassType.Concrete, new[] { "BATTERY", "CAPACITORBANK", "HARMONICFILTER", "INDUCTORBANK", "UPS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowTreatmentDeviceType", "IfcDistributionFlowElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDuctSilencerType", "IfcFlowTreatmentDeviceType", ClassType.Concrete, new[] { "FLATOVAL", "RECTANGULAR", "ROUND", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFilterType", "IfcFlowTreatmentDeviceType", ClassType.Concrete, new[] { "AIRPARTICLEFILTER", "ODORFILTER", "OILFILTER", "STRAINER", "WATERFILTER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcDistributionControlElementType", "IfcDistributionElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcActuatorType", "IfcDistributionControlElementType", ClassType.Concrete, new[] { "ELECTRICACTUATOR", "HANDOPERATEDACTUATOR", "HYDRAULICACTUATOR", "PNEUMATICACTUATOR", "THERMOSTATICACTUATOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcAlarmType", "IfcDistributionControlElementType", ClassType.Concrete, new[] { "BELL", "BREAKGLASSBUTTON", "LIGHT", "MANUALPULLBOX", "SIREN", "WHISTLE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcControllerType", "IfcDistributionControlElementType", ClassType.Concrete, new[] { "FLOATING", "PROPORTIONAL", "PROPORTIONALINTEGRAL", "PROPORTIONALINTEGRALDERIVATIVE", "TIMEDTWOPOSITION", "TWOPOSITION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFlowInstrumentType", "IfcDistributionControlElementType", ClassType.Concrete, new[] { "PRESSUREGAUGE", "THERMOMETER", "AMMETER", "FREQUENCYMETER", "POWERFACTORMETER", "PHASEANGLEMETER", "VOLTMETER_PEAK", "VOLTMETER_RMS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcSensorType", "IfcDistributionControlElementType", ClassType.Concrete, new[] { "CO2SENSOR", "FIRESENSOR", "FLOWSENSOR", "GASSENSOR", "HEATSENSOR", "HUMIDITYSENSOR", "LIGHTSENSOR", "MOISTURESENSOR", "MOVEMENTSENSOR", "PRESSURESENSOR", "SMOKESENSOR", "SOUNDSENSOR", "TEMPERATURESENSOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcElementComponentType", "IfcElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcDiscreteAccessoryType", "IfcElementComponentType", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcVibrationIsolatorType", "IfcDiscreteAccessoryType", ClassType.Concrete, new[] { "COMPRESSION", "SPRING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFastenerType", "IfcElementComponentType", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcMechanicalFastenerType", "IfcFastenerType", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBuildingElementType", "IfcElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcBeamType", "IfcBuildingElementType", ClassType.Concrete, new[] { "BEAM", "JOIST", "LINTEL", "T_BEAM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcColumnType", "IfcBuildingElementType", ClassType.Concrete, new[] { "COLUMN", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCurtainWallType", "IfcBuildingElementType", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcMemberType", "IfcBuildingElementType", ClassType.Concrete, new[] { "BRACE", "CHORD", "COLLAR", "MEMBER", "MULLION", "PLATE", "POST", "PURLIN", "RAFTER", "STRINGER", "STRUT", "STUD", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcPlateType", "IfcBuildingElementType", ClassType.Concrete, new[] { "CURTAIN_PANEL", "SHEET", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcRailingType", "IfcBuildingElementType", ClassType.Concrete, new[] { "HANDRAIL", "GUARDRAIL", "BALUSTRADE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcRampFlightType", "IfcBuildingElementType", ClassType.Concrete, new[] { "STRAIGHT", "SPIRAL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcSlabType", "IfcBuildingElementType", ClassType.Concrete, new[] { "FLOOR", "ROOF", "LANDING", "BASESLAB", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcStairFlightType", "IfcBuildingElementType", ClassType.Concrete, new[] { "STRAIGHT", "WINDER", "SPIRAL", "CURVED", "FREEFORM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcWallType", "IfcBuildingElementType", ClassType.Concrete, new[] { "STANDARD", "POLYGONAL", "SHEAR", "ELEMENTEDWALL", "PLUMBINGWALL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcBuildingElementProxyType", "IfcBuildingElementType", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcCoveringType", "IfcBuildingElementType", ClassType.Concrete, new[] { "CEILING", "FLOORING", "CLADDING", "ROOFING", "INSULATION", "MEMBRANE", "SLEEVING", "WRAPPING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcFurnishingElementType", "IfcElementType", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcFurnitureType", "IfcFurnishingElementType", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSystemFurnitureElementType", "IfcFurnishingElementType", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSpatialStructureElementType", "IfcElementType", ClassType.Abstract, null));
			schemaIFC2x3.Add(new ClassInfo("IfcSpaceType", "IfcSpatialStructureElementType", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcTransportElementType", "IfcElementType", ClassType.Concrete, new[] { "ELEVATOR", "ESCALATOR", "MOVINGWALKWAY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC2x3.Add(new ClassInfo("IfcDoorStyle", "IfcTypeProduct", ClassType.Concrete, null));
			schemaIFC2x3.Add(new ClassInfo("IfcWindowStyle", "IfcTypeProduct", ClassType.Concrete, null));

		}
		static partial void GetClassesIFC4()
		{
			schemaIFC4 = new SchemaInfo();
			schemaIFC4.Add(new ClassInfo("IfcObject", "IfcObjectDefinition", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcProduct", "IfcObject", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcElement", "IfcProduct", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcBuildingElement", "IfcElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcFooting", "IfcBuildingElement", ClassType.Concrete, new[] { "CAISSON_FOUNDATION", "FOOTING_BEAM", "PAD_FOOTING", "PILE_CAP", "STRIP_FOOTING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPile", "IfcBuildingElement", ClassType.Concrete, new[] { "BORED", "DRIVEN", "JETGROUTING", "COHESION", "FRICTION", "SUPPORT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcBeam", "IfcBuildingElement", ClassType.Concrete, new[] { "BEAM", "JOIST", "HOLLOWCORE", "LINTEL", "SPANDREL", "T_BEAM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcBeamStandardCase", "IfcBeam", ClassType.Concrete, new[] { "BEAM", "JOIST", "HOLLOWCORE", "LINTEL", "SPANDREL", "T_BEAM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcBuildingElementProxy", "IfcBuildingElement", ClassType.Concrete, new[] { "COMPLEX", "ELEMENT", "PARTIAL", "PROVISIONFORVOID", "PROVISIONFORSPACE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcChimney", "IfcBuildingElement", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcColumn", "IfcBuildingElement", ClassType.Concrete, new[] { "COLUMN", "PILASTER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcColumnStandardCase", "IfcColumn", ClassType.Concrete, new[] { "COLUMN", "PILASTER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCovering", "IfcBuildingElement", ClassType.Concrete, new[] { "CEILING", "FLOORING", "CLADDING", "ROOFING", "MOLDING", "SKIRTINGBOARD", "INSULATION", "MEMBRANE", "SLEEVING", "WRAPPING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCurtainWall", "IfcBuildingElement", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDoor", "IfcBuildingElement", ClassType.Concrete, new[] { "DOOR", "GATE", "TRAPDOOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDoorStandardCase", "IfcDoor", ClassType.Concrete, new[] { "DOOR", "GATE", "TRAPDOOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcMember", "IfcBuildingElement", ClassType.Concrete, new[] { "BRACE", "CHORD", "COLLAR", "MEMBER", "MULLION", "PLATE", "POST", "PURLIN", "RAFTER", "STRINGER", "STRUT", "STUD", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcMemberStandardCase", "IfcMember", ClassType.Concrete, new[] { "BRACE", "CHORD", "COLLAR", "MEMBER", "MULLION", "PLATE", "POST", "PURLIN", "RAFTER", "STRINGER", "STRUT", "STUD", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPlate", "IfcBuildingElement", ClassType.Concrete, new[] { "CURTAIN_PANEL", "SHEET", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPlateStandardCase", "IfcPlate", ClassType.Concrete, new[] { "CURTAIN_PANEL", "SHEET", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcRailing", "IfcBuildingElement", ClassType.Concrete, new[] { "HANDRAIL", "GUARDRAIL", "BALUSTRADE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcRamp", "IfcBuildingElement", ClassType.Concrete, new[] { "STRAIGHT_RUN_RAMP", "TWO_STRAIGHT_RUN_RAMP", "QUARTER_TURN_RAMP", "TWO_QUARTER_TURN_RAMP", "HALF_TURN_RAMP", "SPIRAL_RAMP", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcRampFlight", "IfcBuildingElement", ClassType.Concrete, new[] { "STRAIGHT", "SPIRAL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcRoof", "IfcBuildingElement", ClassType.Concrete, new[] { "FLAT_ROOF", "SHED_ROOF", "GABLE_ROOF", "HIP_ROOF", "HIPPED_GABLE_ROOF", "GAMBREL_ROOF", "MANSARD_ROOF", "BARREL_ROOF", "RAINBOW_ROOF", "BUTTERFLY_ROOF", "PAVILION_ROOF", "DOME_ROOF", "FREEFORM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcShadingDevice", "IfcBuildingElement", ClassType.Concrete, new[] { "JALOUSIE", "SHUTTER", "AWNING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSlab", "IfcBuildingElement", ClassType.Concrete, new[] { "FLOOR", "ROOF", "LANDING", "BASESLAB", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSlabElementedCase", "IfcSlab", ClassType.Concrete, new[] { "FLOOR", "ROOF", "LANDING", "BASESLAB", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSlabStandardCase", "IfcSlab", ClassType.Concrete, new[] { "FLOOR", "ROOF", "LANDING", "BASESLAB", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStair", "IfcBuildingElement", ClassType.Concrete, new[] { "STRAIGHT_RUN_STAIR", "TWO_STRAIGHT_RUN_STAIR", "QUARTER_WINDING_STAIR", "QUARTER_TURN_STAIR", "HALF_WINDING_STAIR", "HALF_TURN_STAIR", "TWO_QUARTER_WINDING_STAIR", "TWO_QUARTER_TURN_STAIR", "THREE_QUARTER_WINDING_STAIR", "THREE_QUARTER_TURN_STAIR", "SPIRAL_STAIR", "DOUBLE_RETURN_STAIR", "CURVED_RUN_STAIR", "TWO_CURVED_RUN_STAIR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStairFlight", "IfcBuildingElement", ClassType.Concrete, new[] { "STRAIGHT", "WINDER", "SPIRAL", "CURVED", "FREEFORM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWall", "IfcBuildingElement", ClassType.Concrete, new[] { "MOVABLE", "PARAPET", "PARTITIONING", "PLUMBINGWALL", "SHEAR", "SOLIDWALL", "STANDARD", "POLYGONAL", "ELEMENTEDWALL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWallElementedCase", "IfcWall", ClassType.Concrete, new[] { "MOVABLE", "PARAPET", "PARTITIONING", "PLUMBINGWALL", "SHEAR", "SOLIDWALL", "STANDARD", "POLYGONAL", "ELEMENTEDWALL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWallStandardCase", "IfcWall", ClassType.Concrete, new[] { "MOVABLE", "PARAPET", "PARTITIONING", "PLUMBINGWALL", "SHEAR", "SOLIDWALL", "STANDARD", "POLYGONAL", "ELEMENTEDWALL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWindow", "IfcBuildingElement", ClassType.Concrete, new[] { "WINDOW", "SKYLIGHT", "LIGHTDOME", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWindowStandardCase", "IfcWindow", ClassType.Concrete, new[] { "WINDOW", "SKYLIGHT", "LIGHTDOME", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcElementComponent", "IfcElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcReinforcingElement", "IfcElementComponent", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcReinforcingBar", "IfcReinforcingElement", ClassType.Concrete, new[] { "ANCHORING", "EDGE", "LIGATURE", "MAIN", "PUNCHING", "RING", "SHEAR", "STUD", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcReinforcingMesh", "IfcReinforcingElement", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcTendon", "IfcReinforcingElement", ClassType.Concrete, new[] { "BAR", "COATED", "STRAND", "WIRE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcTendonAnchor", "IfcReinforcingElement", ClassType.Concrete, new[] { "COUPLER", "FIXED_END", "TENSIONING_END", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcBuildingElementPart", "IfcElementComponent", ClassType.Concrete, new[] { "INSULATION", "PRECASTPANEL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDiscreteAccessory", "IfcElementComponent", ClassType.Concrete, new[] { "ANCHORPLATE", "BRACKET", "SHOE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFastener", "IfcElementComponent", ClassType.Concrete, new[] { "GLUE", "MORTAR", "WELD", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcMechanicalFastener", "IfcElementComponent", ClassType.Concrete, new[] { "ANCHORBOLT", "BOLT", "DOWEL", "NAIL", "NAILPLATE", "RIVET", "SCREW", "SHEARCONNECTOR", "STAPLE", "STUDSHEARCONNECTOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcVibrationIsolator", "IfcElementComponent", ClassType.Concrete, new[] { "COMPRESSION", "SPRING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFeatureElement", "IfcElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcSurfaceFeature", "IfcFeatureElement", ClassType.Concrete, new[] { "MARK", "TAG", "TREATMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFeatureElementSubtraction", "IfcFeatureElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcVoidingFeature", "IfcFeatureElementSubtraction", ClassType.Concrete, new[] { "CUTOUT", "NOTCH", "HOLE", "MITER", "CHAMFER", "EDGE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcOpeningElement", "IfcFeatureElementSubtraction", ClassType.Concrete, new[] { "OPENING", "RECESS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcOpeningStandardCase", "IfcOpeningElement", ClassType.Concrete, new[] { "OPENING", "RECESS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFeatureElementAddition", "IfcFeatureElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcProjectionElement", "IfcFeatureElementAddition", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFurnishingElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcFurniture", "IfcFurnishingElement", ClassType.Concrete, new[] { "CHAIR", "TABLE", "DESK", "BED", "FILECABINET", "SHELF", "SOFA", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSystemFurnitureElement", "IfcFurnishingElement", ClassType.Concrete, new[] { "PANEL", "WORKSURFACE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDistributionElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcDistributionFlowElement", "IfcDistributionElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcDistributionChamberElement", "IfcDistributionFlowElement", ClassType.Concrete, new[] { "FORMEDDUCT", "INSPECTIONCHAMBER", "INSPECTIONPIT", "MANHOLE", "METERCHAMBER", "SUMP", "TRENCH", "VALVECHAMBER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcEnergyConversionDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcAirToAirHeatRecovery", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "FIXEDPLATECOUNTERFLOWEXCHANGER", "FIXEDPLATECROSSFLOWEXCHANGER", "FIXEDPLATEPARALLELFLOWEXCHANGER", "ROTARYWHEEL", "RUNAROUNDCOILLOOP", "HEATPIPE", "TWINTOWERENTHALPYRECOVERYLOOPS", "THERMOSIPHONSEALEDTUBEHEATEXCHANGERS", "THERMOSIPHONCOILTYPEHEATEXCHANGERS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcBoiler", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "WATER", "STEAM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcBurner", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcChiller", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "AIRCOOLED", "WATERCOOLED", "HEATRECOVERY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCoil", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "DXCOOLINGCOIL", "ELECTRICHEATINGCOIL", "GASHEATINGCOIL", "HYDRONICCOIL", "STEAMHEATINGCOIL", "WATERCOOLINGCOIL", "WATERHEATINGCOIL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCondenser", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "AIRCOOLED", "EVAPORATIVECOOLED", "WATERCOOLED", "WATERCOOLEDBRAZEDPLATE", "WATERCOOLEDSHELLCOIL", "WATERCOOLEDSHELLTUBE", "WATERCOOLEDTUBEINTUBE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCooledBeam", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "ACTIVE", "PASSIVE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCoolingTower", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "NATURALDRAFT", "MECHANICALINDUCEDDRAFT", "MECHANICALFORCEDDRAFT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcEngine", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "EXTERNALCOMBUSTION", "INTERNALCOMBUSTION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcEvaporativeCooler", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER", "DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER", "DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER", "DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER", "DIRECTEVAPORATIVEAIRWASHER", "INDIRECTEVAPORATIVEPACKAGEAIRCOOLER", "INDIRECTEVAPORATIVEWETCOIL", "INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER", "INDIRECTDIRECTCOMBINATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcEvaporator", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "DIRECTEXPANSION", "DIRECTEXPANSIONSHELLANDTUBE", "DIRECTEXPANSIONTUBEINTUBE", "DIRECTEXPANSIONBRAZEDPLATE", "FLOODEDSHELLANDTUBE", "SHELLANDCOIL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcHeatExchanger", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "PLATE", "SHELLANDTUBE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcHumidifier", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "STEAMINJECTION", "ADIABATICAIRWASHER", "ADIABATICPAN", "ADIABATICWETTEDELEMENT", "ADIABATICATOMIZING", "ADIABATICULTRASONIC", "ADIABATICRIGIDMEDIA", "ADIABATICCOMPRESSEDAIRNOZZLE", "ASSISTEDELECTRIC", "ASSISTEDNATURALGAS", "ASSISTEDPROPANE", "ASSISTEDBUTANE", "ASSISTEDSTEAM", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcTubeBundle", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "FINNED", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcUnitaryEquipment", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "AIRHANDLER", "AIRCONDITIONINGUNIT", "DEHUMIDIFIER", "SPLITSYSTEM", "ROOFTOPUNIT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcElectricGenerator", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "CHP", "ENGINEGENERATOR", "STANDALONE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcElectricMotor", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "DC", "INDUCTION", "POLYPHASE", "RELUCTANCESYNCHRONOUS", "SYNCHRONOUS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcMotorConnection", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "BELTDRIVE", "COUPLING", "DIRECTDRIVE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSolarDevice", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "SOLARCOLLECTOR", "SOLARPANEL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcTransformer", "IfcEnergyConversionDevice", ClassType.Concrete, new[] { "CURRENT", "FREQUENCY", "INVERTER", "RECTIFIER", "VOLTAGE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowController", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcAirTerminalBox", "IfcFlowController", ClassType.Concrete, new[] { "CONSTANTFLOW", "VARIABLEFLOWPRESSUREDEPENDANT", "VARIABLEFLOWPRESSUREINDEPENDANT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDamper", "IfcFlowController", ClassType.Concrete, new[] { "BACKDRAFTDAMPER", "BALANCINGDAMPER", "BLASTDAMPER", "CONTROLDAMPER", "FIREDAMPER", "FIRESMOKEDAMPER", "FUMEHOODEXHAUST", "GRAVITYDAMPER", "GRAVITYRELIEFDAMPER", "RELIEFDAMPER", "SMOKEDAMPER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowMeter", "IfcFlowController", ClassType.Concrete, new[] { "ENERGYMETER", "GASMETER", "OILMETER", "WATERMETER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcValve", "IfcFlowController", ClassType.Concrete, new[] { "AIRRELEASE", "ANTIVACUUM", "CHANGEOVER", "CHECK", "COMMISSIONING", "DIVERTING", "DRAWOFFCOCK", "DOUBLECHECK", "DOUBLEREGULATING", "FAUCET", "FLUSHING", "GASCOCK", "GASTAP", "ISOLATING", "MIXING", "PRESSUREREDUCING", "PRESSURERELIEF", "REGULATING", "SAFETYCUTOFF", "STEAMTRAP", "STOPCOCK", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcElectricDistributionBoard", "IfcFlowController", ClassType.Concrete, new[] { "CONSUMERUNIT", "DISTRIBUTIONBOARD", "MOTORCONTROLCENTRE", "SWITCHBOARD", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcElectricTimeControl", "IfcFlowController", ClassType.Concrete, new[] { "TIMECLOCK", "TIMEDELAY", "RELAY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcProtectiveDevice", "IfcFlowController", ClassType.Concrete, new[] { "CIRCUITBREAKER", "EARTHLEAKAGECIRCUITBREAKER", "EARTHINGSWITCH", "FUSEDISCONNECTOR", "RESIDUALCURRENTCIRCUITBREAKER", "RESIDUALCURRENTSWITCH", "VARISTOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSwitchingDevice", "IfcFlowController", ClassType.Concrete, new[] { "CONTACTOR", "DIMMERSWITCH", "EMERGENCYSTOP", "KEYPAD", "MOMENTARYSWITCH", "SELECTORSWITCH", "STARTER", "SWITCHDISCONNECTOR", "TOGGLESWITCH", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowFitting", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcDuctFitting", "IfcFlowFitting", ClassType.Concrete, new[] { "BEND", "CONNECTOR", "ENTRY", "EXIT", "JUNCTION", "OBSTRUCTION", "TRANSITION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPipeFitting", "IfcFlowFitting", ClassType.Concrete, new[] { "BEND", "CONNECTOR", "ENTRY", "EXIT", "JUNCTION", "OBSTRUCTION", "TRANSITION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCableCarrierFitting", "IfcFlowFitting", ClassType.Concrete, new[] { "BEND", "CROSS", "REDUCER", "TEE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCableFitting", "IfcFlowFitting", ClassType.Concrete, new[] { "CONNECTOR", "ENTRY", "EXIT", "JUNCTION", "TRANSITION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcJunctionBox", "IfcFlowFitting", ClassType.Concrete, new[] { "DATA", "POWER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowMovingDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcCompressor", "IfcFlowMovingDevice", ClassType.Concrete, new[] { "DYNAMIC", "RECIPROCATING", "ROTARY", "SCROLL", "TROCHOIDAL", "SINGLESTAGE", "BOOSTER", "OPENTYPE", "HERMETIC", "SEMIHERMETIC", "WELDEDSHELLHERMETIC", "ROLLINGPISTON", "ROTARYVANE", "SINGLESCREW", "TWINSCREW", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFan", "IfcFlowMovingDevice", ClassType.Concrete, new[] { "CENTRIFUGALFORWARDCURVED", "CENTRIFUGALRADIAL", "CENTRIFUGALBACKWARDINCLINEDCURVED", "CENTRIFUGALAIRFOIL", "TUBEAXIAL", "VANEAXIAL", "PROPELLORAXIAL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPump", "IfcFlowMovingDevice", ClassType.Concrete, new[] { "CIRCULATOR", "ENDSUCTION", "SPLITCASE", "SUBMERSIBLEPUMP", "SUMPPUMP", "VERTICALINLINE", "VERTICALTURBINE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowSegment", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcDuctSegment", "IfcFlowSegment", ClassType.Concrete, new[] { "RIGIDSEGMENT", "FLEXIBLESEGMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPipeSegment", "IfcFlowSegment", ClassType.Concrete, new[] { "CULVERT", "FLEXIBLESEGMENT", "RIGIDSEGMENT", "GUTTER", "SPOOL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCableCarrierSegment", "IfcFlowSegment", ClassType.Concrete, new[] { "CABLELADDERSEGMENT", "CABLETRAYSEGMENT", "CABLETRUNKINGSEGMENT", "CONDUITSEGMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCableSegment", "IfcFlowSegment", ClassType.Concrete, new[] { "BUSBARSEGMENT", "CABLESEGMENT", "CONDUCTORSEGMENT", "CORESEGMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowStorageDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcTank", "IfcFlowStorageDevice", ClassType.Concrete, new[] { "BASIN", "BREAKPRESSURE", "EXPANSION", "FEEDANDEXPANSION", "PRESSUREVESSEL", "STORAGE", "VESSEL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcElectricFlowStorageDevice", "IfcFlowStorageDevice", ClassType.Concrete, new[] { "BATTERY", "CAPACITORBANK", "HARMONICFILTER", "INDUCTORBANK", "UPS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowTerminal", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcFireSuppressionTerminal", "IfcFlowTerminal", ClassType.Concrete, new[] { "BREECHINGINLET", "FIREHYDRANT", "HOSEREEL", "SPRINKLER", "SPRINKLERDEFLECTOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSanitaryTerminal", "IfcFlowTerminal", ClassType.Concrete, new[] { "BATH", "BIDET", "CISTERN", "SHOWER", "SINK", "SANITARYFOUNTAIN", "TOILETPAN", "URINAL", "WASHHANDBASIN", "WCSEAT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStackTerminal", "IfcFlowTerminal", ClassType.Concrete, new[] { "BIRDCAGE", "COWL", "RAINWATERHOPPER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWasteTerminal", "IfcFlowTerminal", ClassType.Concrete, new[] { "FLOORTRAP", "FLOORWASTE", "GULLYSUMP", "GULLYTRAP", "ROOFDRAIN", "WASTEDISPOSALUNIT", "WASTETRAP", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcAirTerminal", "IfcFlowTerminal", ClassType.Concrete, new[] { "DIFFUSER", "GRILLE", "LOUVRE", "REGISTER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcMedicalDevice", "IfcFlowTerminal", ClassType.Concrete, new[] { "AIRSTATION", "FEEDAIRUNIT", "OXYGENGENERATOR", "OXYGENPLANT", "VACUUMSTATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSpaceHeater", "IfcFlowTerminal", ClassType.Concrete, new[] { "CONVECTOR", "RADIATOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcAudioVisualAppliance", "IfcFlowTerminal", ClassType.Concrete, new[] { "AMPLIFIER", "CAMERA", "DISPLAY", "MICROPHONE", "PLAYER", "PROJECTOR", "RECEIVER", "SPEAKER", "SWITCHER", "TELEPHONE", "TUNER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCommunicationsAppliance", "IfcFlowTerminal", ClassType.Concrete, new[] { "ANTENNA", "COMPUTER", "FAX", "GATEWAY", "MODEM", "NETWORKAPPLIANCE", "NETWORKBRIDGE", "NETWORKHUB", "PRINTER", "REPEATER", "ROUTER", "SCANNER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcElectricAppliance", "IfcFlowTerminal", ClassType.Concrete, new[] { "DISHWASHER", "ELECTRICCOOKER", "FREESTANDINGELECTRICHEATER", "FREESTANDINGFAN", "FREESTANDINGWATERHEATER", "FREESTANDINGWATERCOOLER", "FREEZER", "FRIDGE_FREEZER", "HANDDRYER", "KITCHENMACHINE", "MICROWAVE", "PHOTOCOPIER", "REFRIGERATOR", "TUMBLEDRYER", "VENDINGMACHINE", "WASHINGMACHINE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcLamp", "IfcFlowTerminal", ClassType.Concrete, new[] { "COMPACTFLUORESCENT", "FLUORESCENT", "HALOGEN", "HIGHPRESSUREMERCURY", "HIGHPRESSURESODIUM", "LED", "METALHALIDE", "OLED", "TUNGSTENFILAMENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcLightFixture", "IfcFlowTerminal", ClassType.Concrete, new[] { "POINTSOURCE", "DIRECTIONSOURCE", "SECURITYLIGHTING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcOutlet", "IfcFlowTerminal", ClassType.Concrete, new[] { "AUDIOVISUALOUTLET", "COMMUNICATIONSOUTLET", "POWEROUTLET", "DATAOUTLET", "TELEPHONEOUTLET", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowTreatmentDevice", "IfcDistributionFlowElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcInterceptor", "IfcFlowTreatmentDevice", ClassType.Concrete, new[] { "CYCLONIC", "GREASE", "OIL", "PETROL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDuctSilencer", "IfcFlowTreatmentDevice", ClassType.Concrete, new[] { "FLATOVAL", "RECTANGULAR", "ROUND", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFilter", "IfcFlowTreatmentDevice", ClassType.Concrete, new[] { "AIRPARTICLEFILTER", "COMPRESSEDAIRFILTER", "ODORFILTER", "OILFILTER", "STRAINER", "WATERFILTER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDistributionControlElement", "IfcDistributionElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcProtectiveDeviceTrippingUnit", "IfcDistributionControlElement", ClassType.Concrete, new[] { "ELECTRONIC", "ELECTROMAGNETIC", "RESIDUALCURRENT", "THERMAL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcActuator", "IfcDistributionControlElement", ClassType.Concrete, new[] { "ELECTRICACTUATOR", "HANDOPERATEDACTUATOR", "HYDRAULICACTUATOR", "PNEUMATICACTUATOR", "THERMOSTATICACTUATOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcAlarm", "IfcDistributionControlElement", ClassType.Concrete, new[] { "BELL", "BREAKGLASSBUTTON", "LIGHT", "MANUALPULLBOX", "SIREN", "WHISTLE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcController", "IfcDistributionControlElement", ClassType.Concrete, new[] { "FLOATING", "PROGRAMMABLE", "PROPORTIONAL", "MULTIPOSITION", "TWOPOSITION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcFlowInstrument", "IfcDistributionControlElement", ClassType.Concrete, new[] { "PRESSUREGAUGE", "THERMOMETER", "AMMETER", "FREQUENCYMETER", "POWERFACTORMETER", "PHASEANGLEMETER", "VOLTMETER_PEAK", "VOLTMETER_RMS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSensor", "IfcDistributionControlElement", ClassType.Concrete, new[] { "COSENSOR", "CO2SENSOR", "CONDUCTANCESENSOR", "CONTACTSENSOR", "FIRESENSOR", "FLOWSENSOR", "FROSTSENSOR", "GASSENSOR", "HEATSENSOR", "HUMIDITYSENSOR", "IDENTIFIERSENSOR", "IONCONCENTRATIONSENSOR", "LEVELSENSOR", "LIGHTSENSOR", "MOISTURESENSOR", "MOVEMENTSENSOR", "PHSENSOR", "PRESSURESENSOR", "RADIATIONSENSOR", "RADIOACTIVITYSENSOR", "SMOKESENSOR", "SOUNDSENSOR", "TEMPERATURESENSOR", "WINDSENSOR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcUnitaryControlElement", "IfcDistributionControlElement", ClassType.Concrete, new[] { "ALARMPANEL", "CONTROLPANEL", "GASDETECTIONPANEL", "INDICATORPANEL", "MIMICPANEL", "HUMIDISTAT", "THERMOSTAT", "WEATHERSTATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCivilElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcElementAssembly", "IfcElement", ClassType.Concrete, new[] { "ACCESSORY_ASSEMBLY", "ARCH", "BEAM_GRID", "BRACED_FRAME", "GIRDER", "REINFORCEMENT_UNIT", "RIGID_FRAME", "SLAB_FIELD", "TRUSS", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcGeographicElement", "IfcElement", ClassType.Concrete, new[] { "TERRAIN", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcTransportElement", "IfcElement", ClassType.Concrete, new[] { "ELEVATOR", "ESCALATOR", "MOVINGWALKWAY", "CRANEWAY", "LIFTINGGEAR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcVirtualElement", "IfcElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralActivity", "IfcProduct", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralAction", "IfcStructuralActivity", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralCurveAction", "IfcStructuralAction", ClassType.Concrete, new[] { "CONST", "LINEAR", "POLYGONAL", "EQUIDISTANT", "SINUS", "PARABOLA", "DISCRETE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralLinearAction", "IfcStructuralCurveAction", ClassType.Concrete, new[] { "CONST", "LINEAR", "POLYGONAL", "EQUIDISTANT", "SINUS", "PARABOLA", "DISCRETE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralSurfaceAction", "IfcStructuralAction", ClassType.Concrete, new[] { "CONST", "BILINEAR", "DISCRETE", "ISOCONTOUR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralPlanarAction", "IfcStructuralSurfaceAction", ClassType.Concrete, new[] { "CONST", "BILINEAR", "DISCRETE", "ISOCONTOUR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralPointAction", "IfcStructuralAction", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralReaction", "IfcStructuralActivity", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralCurveReaction", "IfcStructuralReaction", ClassType.Concrete, new[] { "CONST", "LINEAR", "POLYGONAL", "EQUIDISTANT", "SINUS", "PARABOLA", "DISCRETE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralPointReaction", "IfcStructuralReaction", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralSurfaceReaction", "IfcStructuralReaction", ClassType.Concrete, new[] { "CONST", "BILINEAR", "DISCRETE", "ISOCONTOUR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralItem", "IfcProduct", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralConnection", "IfcStructuralItem", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralCurveConnection", "IfcStructuralConnection", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralPointConnection", "IfcStructuralConnection", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralSurfaceConnection", "IfcStructuralConnection", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralMember", "IfcStructuralItem", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralCurveMember", "IfcStructuralMember", ClassType.Concrete, new[] { "RIGID_JOINED_MEMBER", "PIN_JOINED_MEMBER", "CABLE", "TENSION_MEMBER", "COMPRESSION_MEMBER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralCurveMemberVarying", "IfcStructuralCurveMember", ClassType.Concrete, new[] { "RIGID_JOINED_MEMBER", "PIN_JOINED_MEMBER", "CABLE", "TENSION_MEMBER", "COMPRESSION_MEMBER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralSurfaceMember", "IfcStructuralMember", ClassType.Concrete, new[] { "BENDING_ELEMENT", "MEMBRANE_ELEMENT", "SHELL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralSurfaceMemberVarying", "IfcStructuralSurfaceMember", ClassType.Concrete, new[] { "BENDING_ELEMENT", "MEMBRANE_ELEMENT", "SHELL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPort", "IfcProduct", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcDistributionPort", "IfcPort", ClassType.Concrete, new[] { "CABLE", "CABLECARRIER", "DUCT", "PIPE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPositioningElement", "IfcProduct", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcLinearPositioningElement", "IfcPositioningElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcAlignment", "IfcLinearPositioningElement", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcReferent", "IfcPositioningElement", ClassType.Concrete, new[] { "KILOPOINT", "MILEPOINT", "STATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcAnnotation", "IfcProduct", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcSpatialElement", "IfcProduct", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcSpatialStructureElement", "IfcSpatialElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcBuilding", "IfcSpatialStructureElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcBuildingStorey", "IfcSpatialStructureElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcSite", "IfcSpatialStructureElement", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcSpace", "IfcSpatialStructureElement", ClassType.Concrete, new[] { "SPACE", "PARKING", "GFA", "INTERNAL", "EXTERNAL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcExternalSpatialStructureElement", "IfcSpatialElement", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcExternalSpatialElement", "IfcExternalSpatialStructureElement", ClassType.Concrete, new[] { "EXTERNAL", "EXTERNAL_EARTH", "EXTERNAL_WATER", "EXTERNAL_FIRE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSpatialZone", "IfcSpatialElement", ClassType.Concrete, new[] { "CONSTRUCTION", "FIRESAFETY", "LIGHTING", "OCCUPANCY", "SECURITY", "THERMAL", "TRANSPORT", "VENTILATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcGrid", "IfcProduct", ClassType.Concrete, new[] { "RECTANGULAR", "RADIAL", "TRIANGULAR", "IRREGULAR", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcProxy", "IfcProduct", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcGroup", "IfcObject", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcSystem", "IfcGroup", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralAnalysisModel", "IfcSystem", ClassType.Concrete, new[] { "IN_PLANE_LOADING_2D", "OUT_PLANE_LOADING_2D", "LOADING_3D", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDistributionSystem", "IfcSystem", ClassType.Concrete, new[] { "AIRCONDITIONING", "AUDIOVISUAL", "CHEMICAL", "CHILLEDWATER", "COMMUNICATION", "COMPRESSEDAIR", "CONDENSERWATER", "CONTROL", "CONVEYING", "DATA", "DISPOSAL", "DOMESTICCOLDWATER", "DOMESTICHOTWATER", "DRAINAGE", "EARTHING", "ELECTRICAL", "ELECTROACOUSTIC", "EXHAUST", "FIREPROTECTION", "FUEL", "GAS", "HAZARDOUS", "HEATING", "LIGHTING", "LIGHTNINGPROTECTION", "MUNICIPALSOLIDWASTE", "OIL", "OPERATIONAL", "POWERGENERATION", "RAINWATER", "REFRIGERATION", "SECURITY", "SEWAGE", "SIGNAL", "STORMWATER", "TELEPHONE", "TV", "VACUUM", "VENT", "VENTILATION", "WASTEWATER", "WATERSUPPLY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcDistributionCircuit", "IfcDistributionSystem", ClassType.Concrete, new[] { "AIRCONDITIONING", "AUDIOVISUAL", "CHEMICAL", "CHILLEDWATER", "COMMUNICATION", "COMPRESSEDAIR", "CONDENSERWATER", "CONTROL", "CONVEYING", "DATA", "DISPOSAL", "DOMESTICCOLDWATER", "DOMESTICHOTWATER", "DRAINAGE", "EARTHING", "ELECTRICAL", "ELECTROACOUSTIC", "EXHAUST", "FIREPROTECTION", "FUEL", "GAS", "HAZARDOUS", "HEATING", "LIGHTING", "LIGHTNINGPROTECTION", "MUNICIPALSOLIDWASTE", "OIL", "OPERATIONAL", "POWERGENERATION", "RAINWATER", "REFRIGERATION", "SECURITY", "SEWAGE", "SIGNAL", "STORMWATER", "TELEPHONE", "TV", "VACUUM", "VENT", "VENTILATION", "WASTEWATER", "WATERSUPPLY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcBuildingSystem", "IfcSystem", ClassType.Concrete, new[] { "FENESTRATION", "FOUNDATION", "LOADBEARING", "OUTERSHELL", "SHADING", "TRANSPORT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcZone", "IfcSystem", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcStructuralLoadGroup", "IfcGroup", ClassType.Concrete, new[] { "LOAD_GROUP", "LOAD_CASE", "LOAD_COMBINATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralLoadCase", "IfcStructuralLoadGroup", ClassType.Concrete, new[] { "LOAD_GROUP", "LOAD_CASE", "LOAD_COMBINATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcStructuralResultGroup", "IfcGroup", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcAsset", "IfcGroup", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcInventory", "IfcGroup", ClassType.Concrete, new[] { "ASSETINVENTORY", "SPACEINVENTORY", "FURNITUREINVENTORY", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcControl", "IfcObject", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcActionRequest", "IfcControl", ClassType.Concrete, new[] { "EMAIL", "FAX", "PHONE", "POST", "VERBAL", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCostItem", "IfcControl", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCostSchedule", "IfcControl", ClassType.Concrete, new[] { "BUDGET", "COSTPLAN", "ESTIMATE", "TENDER", "PRICEDBILLOFQUANTITIES", "UNPRICEDBILLOFQUANTITIES", "SCHEDULEOFRATES", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPermit", "IfcControl", ClassType.Concrete, new[] { "ACCESS", "BUILDING", "WORK", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcProjectOrder", "IfcControl", ClassType.Concrete, new[] { "CHANGEORDER", "MAINTENANCEWORKORDER", "MOVEORDER", "PURCHASEORDER", "WORKORDER", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWorkCalendar", "IfcControl", ClassType.Concrete, new[] { "FIRSTSHIFT", "SECONDSHIFT", "THIRDSHIFT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWorkControl", "IfcControl", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcWorkPlan", "IfcWorkControl", ClassType.Concrete, new[] { "ACTUAL", "BASELINE", "PLANNED", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcWorkSchedule", "IfcWorkControl", ClassType.Concrete, new[] { "ACTUAL", "BASELINE", "PLANNED", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcPerformanceHistory", "IfcControl", ClassType.Concrete, new[] { "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcActor", "IfcObject", ClassType.Concrete, null));
			schemaIFC4.Add(new ClassInfo("IfcOccupant", "IfcActor", ClassType.Concrete, new[] { "ASSIGNEE", "ASSIGNOR", "LESSEE", "LESSOR", "LETTINGAGENT", "OWNER", "TENANT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcProcess", "IfcObject", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcEvent", "IfcProcess", ClassType.Concrete, new[] { "STARTEVENT", "ENDEVENT", "INTERMEDIATEEVENT", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcProcedure", "IfcProcess", ClassType.Concrete, new[] { "ADVICE_CAUTION", "ADVICE_NOTE", "ADVICE_WARNING", "CALIBRATION", "DIAGNOSTIC", "SHUTDOWN", "STARTUP", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcTask", "IfcProcess", ClassType.Concrete, new[] { "ATTENDANCE", "CONSTRUCTION", "DEMOLITION", "DISMANTLE", "DISPOSAL", "INSTALLATION", "LOGISTIC", "MAINTENANCE", "MOVE", "OPERATION", "REMOVAL", "RENOVATION", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcResource", "IfcObject", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcConstructionResource", "IfcResource", ClassType.Abstract, null));
			schemaIFC4.Add(new ClassInfo("IfcConstructionEquipmentResource", "IfcConstructionResource", ClassType.Concrete, new[] { "DEMOLISHING", "EARTHMOVING", "ERECTING", "HEATING", "LIGHTING", "PAVING", "PUMPING", "TRANSPORTING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcConstructionMaterialResource", "IfcConstructionResource", ClassType.Concrete, new[] { "AGGREGATES", "CONCRETE", "DRYWALL", "FUEL", "GYPSUM", "MASONRY", "METAL", "PLASTIC", "WOOD", "NOTDEFINED", "USERDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcConstructionProductResource", "IfcConstructionResource", ClassType.Concrete, new[] { "ASSEMBLY", "FORMWORK", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcCrewResource", "IfcConstructionResource", ClassType.Concrete, new[] { "OFFICE", "SITE", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcLaborResource", "IfcConstructionResource", ClassType.Concrete, new[] { "ADMINISTRATION", "CARPENTRY", "CLEANING", "CONCRETE", "DRYWALL", "ELECTRIC", "FINISHING", "FLOORING", "GENERAL", "HVAC", "LANDSCAPING", "MASONRY", "PAINTING", "PAVING", "PLUMBING", "ROOFING", "SITEGRADING", "STEELWORK", "SURVEYING", "USERDEFINED", "NOTDEFINED" }));
			schemaIFC4.Add(new ClassInfo("IfcSubContractResource", "IfcConstructionResource", ClassType.Concrete, new[] { "PURCHASE", "WORK", "USERDEFINED", "NOTDEFINED" }));
		}
	}
}
