// generated running xbim.xids.generator
using System.Collections.Generic;

namespace Xbim.InformationSpecifications.Helpers
{
	public partial class SchemaInfo
	{
		public static Dictionary<string, IfcMeasureInfo> IfcMeasures = new()
		{
			{ "AmountOfSubstance", new IfcMeasureInfo("AmountOfSubstance", "IfcAmountOfSubstanceMeasure", "Amount of substance", "mole", "mol", "(0, 0, 0, 0, 0, 1, 0)") },
			{ "AreaDensity", new IfcMeasureInfo("AreaDensity", "IfcAreaDensityMeasure", "Area density", "", "Kg/m2", "(-2, 1, 0, 0, 0, 0, 0)") },
			{ "Area", new IfcMeasureInfo("Area", "IfcAreaMeasure", "Area", "square meter", "m2", "(2, 0, 0, 0, 0, 0, 0)") },
			{ "DynamicViscosity", new IfcMeasureInfo("DynamicViscosity", "IfcDynamicViscosityMeasure", "Dynamic viscosity", "", "Pa s", "(-1, 1, -1, 0, 0, 0, 0)") },
			{ "ElectricCapacitance", new IfcMeasureInfo("ElectricCapacitance", "IfcElectricCapacitanceMeasure", "Electric capacitance", "farad", "F", "(-2, 1, 4, 1, 0, 0, 0)") },
			{ "ElectricCharge", new IfcMeasureInfo("ElectricCharge", "IfcElectricChargeMeasure", "Electric charge", "coulomb", "C", "(0, 0, 1, 1, 0, 0, 0)") },
			{ "ElectricConductance", new IfcMeasureInfo("ElectricConductance", "IfcElectricConductanceMeasure", "Electric conductance", "siemens", "S", "(-2, -1, 3, 2, 0, 0, 0)") },
			{ "ElectricCurrent", new IfcMeasureInfo("ElectricCurrent", "IfcElectricCurrentMeasure", "Electric current", "ampere", "A", "(0, 0, 0, 1, 0, 0, 0)") },
			{ "ElectricResistance", new IfcMeasureInfo("ElectricResistance", "IfcElectricResistanceMeasure", "Electric resistance", "ohm", "Ω", "(2, 1, -3, -2, 0, 0, 0)") },
			{ "ElectricVoltage", new IfcMeasureInfo("ElectricVoltage", "IfcElectricVoltageMeasure", "Electric voltage", "volt", "V", "(2, 1, -3, -1, 0, 0, 0)") },
			{ "Energy", new IfcMeasureInfo("Energy", "IfcEnergyMeasure", "Energy", "joule", "J", "(2, 1, -2, 0, 0, 0, 0)") },
			{ "Force", new IfcMeasureInfo("Force", "IfcForceMeasure", "Force", "newton", "N", "(1, 1, -2, 0, 0, 0, 0)") },
			{ "Frequency", new IfcMeasureInfo("Frequency", "IfcFrequencyMeasure", "Frequency", "hertz", "Hz", "(0, 0, -1, 0, 0, 0, 0)") },
			{ "HeatFluxDensity", new IfcMeasureInfo("HeatFluxDensity", "IfcHeatFluxDensityMeasure", "Heat flux density", "", "W/m2", "(0, 1, -3, 0, 0, 0, 0)") },
			{ "Heating", new IfcMeasureInfo("Heating", "IfcHeatingValueMeasure", "Heating", "", "J/K", "(2, 1, -2, 0, -1, 0, 0)") },
			{ "Illuminance", new IfcMeasureInfo("Illuminance", "IfcIlluminanceMeasure", "Illuminance", "lux", "lx", "(-2, 0, 0, 0, 0, 0, 1)") },
			{ "IonConcentration", new IfcMeasureInfo("IonConcentration", "IfcIonConcentrationMeasure", "Ion concentration measure", "", "mol/m3", "(-3, 1, 0, 0, 0, 0, 0)") },
			{ "IsoThermalMoistureCapacity", new IfcMeasureInfo("IsoThermalMoistureCapacity", "IfcIsothermalMoistureCapacityMeasure", "Iso thermal moisture capacity", "", "m3/Kg", "(3, -1, 0, 0, 0, 0, 0)") },
			{ "Length", new IfcMeasureInfo("Length", "IfcLengthMeasure", "Length", "meter", "m", "(1, 0, 0, 0, 0, 0, 0)") },
			{ "Speed", new IfcMeasureInfo("Speed", "IfcLinearVelocityMeasure", "Speed", "", "m/s", "(1, 0, -1, 0, 0, 0, 0)") },
			{ "LuminousFlux", new IfcMeasureInfo("LuminousFlux", "IfcLuminousFluxMeasure", "Luminous flux", "Lumen", "lm", "(0, 0, 0, 0, 0, 0, 1)") },
			{ "LuminousIntensity", new IfcMeasureInfo("LuminousIntensity", "IfcLuminousIntensityMeasure", "Luminous intensity", "candela", "cd", "(0, 0, 0, 0, 0, 0, 1)") },
			{ "MassDensity", new IfcMeasureInfo("MassDensity", "IfcMassDensityMeasure", "Mass density", "", "Kg/m3", "(-3, 1, 0, 0, 0, 0, 0)") },
			{ "MassFlowRate", new IfcMeasureInfo("MassFlowRate", "IfcMassFlowRateMeasure", "Mass flow rate", "", "Kg/s", "(0, 1, -1, 0, 0, 0, 0)") },
			{ "Mass", new IfcMeasureInfo("Mass", "IfcMassMeasure", "Mass", "kilogram", "Kg", "(0, 1, 0, 0, 0, 0, 0)") },
			{ "MassPerLength", new IfcMeasureInfo("MassPerLength", "IfcMassPerLengthMeasure", "Mass per length", "", "Kg/m", "(-1, 1, 0, 0, 0, 0, 0)") },
			{ "ModulusOfElasticity", new IfcMeasureInfo("ModulusOfElasticity", "IfcModulusOfElasticityMeasure", "Modulus of elasticity", "", "N/m2", "(-1, 1, -2, 0, 0, 0, 0)") },
			{ "MoistureDiffusivity", new IfcMeasureInfo("MoistureDiffusivity", "IfcMoistureDiffusivityMeasure", "Moisture diffusivity", "", "m3/s", "(3, 0, -1, 0, 0, 0, 0)") },
			{ "MolecularWeight", new IfcMeasureInfo("MolecularWeight", "IfcMolecularWeightMeasure", "Molecular weight", "", "Kg/mol", "(0, 1, 0, 0, 0, -1, 0)") },
			{ "MomentOfInertia", new IfcMeasureInfo("MomentOfInertia", "IfcMomentOfInertiaMeasure", "Moment of inertia", "", "m4", "(4, 0, 0, 0, 0, 0, 0)") },
			{ "PH", new IfcMeasureInfo("PH", "IfcPHMeasure", "PH", "", "PH", "(0, 0, 0, 0, 0, 0, 0)") },
			{ "PlanarForce", new IfcMeasureInfo("PlanarForce", "IfcPlanarForceMeasure", "Planar force", "", "Pa", "(-1, 1, -2, 0, 0, 0, 0)") },
			{ "Angle", new IfcMeasureInfo("Angle", "IfcPlaneAngleMeasure", "Angle", "radian", "rad", "(0, 0, 0, 0, 0, 0, 0)") },
			{ "PlaneAngle", new IfcMeasureInfo("PlaneAngle", "IfcPlaneAngleMeasure", "Plane angle", "radian", "rad", "(0, 0, 0, 0, 0, 0, 0)") },
			{ "Power", new IfcMeasureInfo("Power", "IfcPowerMeasure", "Power", "watt", "W", "(2, 1, -3, 0, 0, 0, 0") },
			{ "Pressure", new IfcMeasureInfo("Pressure", "IfcPressureMeasure", "Pressure", "pascal", "Pa", "(-1, 1, -2, 0, 0, 0, 0)") },
			{ "RadioActivity", new IfcMeasureInfo("RadioActivity", "IfcRadioActivityMeasure", "Radio activity", "Becqurel", "Bq", "(0, 0, -1, 0, 0, 0, 0)") },
			{ "Ratio", new IfcMeasureInfo("Ratio", "IfcRatioMeasure", "Ratio", "Percent", "%", "(0, 0, 0, 0, 0, 0, 0)") },
			{ "RotationalFrequency", new IfcMeasureInfo("RotationalFrequency", "IfcRotationalFrequencyMeasure", "Rotational frequency", "hertz", "Hz", "(0, 0, -1, 0, 0, 0, 0)") },
			{ "SectionModulus", new IfcMeasureInfo("SectionModulus", "IfcSectionModulusMeasure", "Section modulus", "", "m3", "(3, 0, 0, 0, 0, 0, 0)") },
			{ "SoundPower", new IfcMeasureInfo("SoundPower", "IfcSoundPowerMeasure", "Sound power", "decibel", "db", "(0, 0, 0, 0, 0, 0, 0)") },
			{ "SoundPressure", new IfcMeasureInfo("SoundPressure", "IfcSoundPressureMeasure", "Sound pressure", "decibel", "db", "(0, 0, 0, 0, 0, 0, 0)") },
			{ "SpecificHeatCapacity", new IfcMeasureInfo("SpecificHeatCapacity", "IfcSpecificHeatCapacityMeasure", "Specific heat capacity", "", "J/Kg K", "(2, 0, -2, 0, -1, 0, 0)") },
			{ "TemperatureRateOfChange", new IfcMeasureInfo("TemperatureRateOfChange", "IfcTemperatureRateOfChangeMeasure", "Temperature rate of change", "", "K/s", "(0, 0, -1, 0, 1, 0, 0)") },
			{ "ThermalConductivity", new IfcMeasureInfo("ThermalConductivity", "IfcThermalConductivityMeasure", "Thermal conductivity", "", "W/m K", "(1, 1, -3, 0, -1, 0, 0)") },
			{ "Temperature", new IfcMeasureInfo("Temperature", "IfcThermodynamicTemperatureMeasure", "Temperature", "kelvin", "K", "(0, 0, 0, 0, 1, 0, 0)") },
			{ "Time", new IfcMeasureInfo("Time", "IfcTimeMeasure", "Time", "second", "s", "(0, 0, 1, 0, 0, 0, 0)") },
			{ "Torque", new IfcMeasureInfo("Torque", "IfcTorqueMeasure", "Torque", "", "N m", "(2, 1, -2, 0, 0, 0, 0)") },
			{ "VaporPermeability", new IfcMeasureInfo("VaporPermeability", "IfcVaporPermeabilityMeasure", "Vapor permeability", "", "Kg / s m Pa", "(0, 0, 1, 0, 0, 0, 0)") },
			{ "Volume", new IfcMeasureInfo("Volume", "IfcVolumeMeasure", "Volume", "cubic meter", "m3", "(3, 0, 0, 0, 0, 0, 0)") },
			{ "VolumetricFlowRate", new IfcMeasureInfo("VolumetricFlowRate", "IfcVolumetricFlowRateMeasure", "Volumetric flow rate", "", "m3/s", "(3, 0, -1, 0, 0, 0, 0)") },
			{ "String", new IfcMeasureInfo("String", "", "", "", "", "") },
			{ "Number", new IfcMeasureInfo("Number", "", "", "", "", "") },
		};
	}
}
