// generated code via xbim.xids.generator, any changes made directly here will be lost

using System.Collections.Generic;

namespace Xbim.InformationSpecifications.Helpers
{
	public partial class SchemaInfo
	{
		static partial void GetRelationTypesIFC2x3(SchemaInfo schema)
		{
			schema.SetRelationType("IfcTypeProduct", new[] { "IfcTypeProduct" });
			schema.SetRelationType("IfcElement", new[] { "IfcElementType" });
			schema.SetRelationType("IfcDistributionElement", new[] { "IfcDistributionElementType" });
			schema.SetRelationType("IfcDistributionFlowElement", new[] { "IfcDistributionFlowElementType" });
			schema.SetRelationType("IfcFlowTerminal", new[] { "IfcFlowTerminalType", "IfcFireSuppressionTerminalType", "IfcSanitaryTerminalType", "IfcStackTerminalType", "IfcWasteTerminalType", "IfcAirTerminalType", "IfcGasTerminalType", "IfcElectricApplianceType", "IfcElectricHeaterType", "IfcLampType", "IfcLightFixtureType", "IfcOutletType" });
			schema.SetRelationType("IfcDistributionChamberElement", new[] { "IfcDistributionChamberElementType" });
			schema.SetRelationType("IfcEnergyConversionDevice", new[] { "IfcEnergyConversionDeviceType", "IfcAirToAirHeatRecoveryType", "IfcBoilerType", "IfcChillerType", "IfcCoilType", "IfcCondenserType", "IfcCooledBeamType", "IfcCoolingTowerType", "IfcEvaporativeCoolerType", "IfcEvaporatorType", "IfcHeatExchangerType", "IfcHumidifierType", "IfcSpaceHeaterType", "IfcTubeBundleType", "IfcUnitaryEquipmentType", "IfcElectricGeneratorType", "IfcElectricMotorType", "IfcMotorConnectionType", "IfcTransformerType" });
			schema.SetRelationType("IfcFlowController", new[] { "IfcFlowControllerType", "IfcAirTerminalBoxType", "IfcDamperType", "IfcFlowMeterType", "IfcValveType", "IfcElectricTimeControlType", "IfcProtectiveDeviceType", "IfcSwitchingDeviceType" });
			schema.SetRelationType("IfcFlowFitting", new[] { "IfcFlowFittingType", "IfcDuctFittingType", "IfcPipeFittingType", "IfcCableCarrierFittingType", "IfcJunctionBoxType" });
			schema.SetRelationType("IfcFlowMovingDevice", new[] { "IfcFlowMovingDeviceType", "IfcCompressorType", "IfcFanType", "IfcPumpType" });
			schema.SetRelationType("IfcFlowSegment", new[] { "IfcFlowSegmentType", "IfcDuctSegmentType", "IfcPipeSegmentType", "IfcCableCarrierSegmentType", "IfcCableSegmentType" });
			schema.SetRelationType("IfcFlowStorageDevice", new[] { "IfcFlowStorageDeviceType", "IfcTankType", "IfcElectricFlowStorageDeviceType" });
			schema.SetRelationType("IfcFlowTreatmentDevice", new[] { "IfcFlowTreatmentDeviceType", "IfcDuctSilencerType", "IfcFilterType" });
			schema.SetRelationType("IfcDistributionControlElement", new[] { "IfcDistributionControlElementType", "IfcActuatorType", "IfcAlarmType", "IfcControllerType", "IfcFlowInstrumentType", "IfcSensorType" });
			schema.SetRelationType("IfcElementComponent", new[] { "IfcElementComponentType" });
			schema.SetRelationType("IfcDiscreteAccessory", new[] { "IfcDiscreteAccessoryType", "IfcVibrationIsolatorType" });
			schema.SetRelationType("IfcFastener", new[] { "IfcFastenerType" });
			schema.SetRelationType("IfcMechanicalFastener", new[] { "IfcMechanicalFastenerType" });
			schema.SetRelationType("IfcBuildingElement", new[] { "IfcBuildingElementType" });
			schema.SetRelationType("IfcBeam", new[] { "IfcBeamType" });
			schema.SetRelationType("IfcColumn", new[] { "IfcColumnType" });
			schema.SetRelationType("IfcCurtainWall", new[] { "IfcCurtainWallType" });
			schema.SetRelationType("IfcMember", new[] { "IfcMemberType" });
			schema.SetRelationType("IfcPlate", new[] { "IfcPlateType" });
			schema.SetRelationType("IfcRailing", new[] { "IfcRailingType" });
			schema.SetRelationType("IfcRampFlight", new[] { "IfcRampFlightType" });
			schema.SetRelationType("IfcSlab", new[] { "IfcSlabType" });
			schema.SetRelationType("IfcStairFlight", new[] { "IfcStairFlightType" });
			schema.SetRelationType("IfcWall", new[] { "IfcWallType" });
			schema.SetRelationType("IfcBuildingElementProxy", new[] { "IfcBuildingElementProxyType" });
			schema.SetRelationType("IfcCovering", new[] { "IfcCoveringType" });
			schema.SetRelationType("IfcFurnishingElement", new[] { "IfcFurnishingElementType", "IfcFurnitureType", "IfcSystemFurnitureElementType" });
			schema.SetRelationType("IfcSpatialStructureElement", new[] { "IfcSpatialStructureElementType" });
			schema.SetRelationType("IfcSpace", new[] { "IfcSpaceType" });
			schema.SetRelationType("IfcTransportElement", new[] { "IfcTransportElementType" });
			schema.SetRelationType("IfcDoor", new[] { "IfcDoorStyle" });
			schema.SetRelationType("IfcWindow", new[] { "IfcWindowStyle" });
		}

		static partial void GetRelationTypesIFC4(SchemaInfo schema)
		{
			schema.SetRelationType("IfcTypeProduct", new[] { "IfcTypeProduct" });
			schema.SetRelationType("IfcElement", new[] { "IfcElementType" });
			schema.SetRelationType("IfcBuildingElement", new[] { "IfcBuildingElementType" });
			schema.SetRelationType("IfcFooting", new[] { "IfcFootingType" });
			schema.SetRelationType("IfcPile", new[] { "IfcPileType" });
			schema.SetRelationType("IfcBeam", new[] { "IfcBeamType" });
			schema.SetRelationType("IfcBuildingElementProxy", new[] { "IfcBuildingElementProxyType" });
			schema.SetRelationType("IfcChimney", new[] { "IfcChimneyType" });
			schema.SetRelationType("IfcColumn", new[] { "IfcColumnType" });
			schema.SetRelationType("IfcCovering", new[] { "IfcCoveringType" });
			schema.SetRelationType("IfcCurtainWall", new[] { "IfcCurtainWallType" });
			schema.SetRelationType("IfcDoor", new[] { "IfcDoorType", "IfcDoorStyle" });
			schema.SetRelationType("IfcMember", new[] { "IfcMemberType" });
			schema.SetRelationType("IfcPlate", new[] { "IfcPlateType" });
			schema.SetRelationType("IfcRailing", new[] { "IfcRailingType" });
			schema.SetRelationType("IfcRampFlight", new[] { "IfcRampFlightType" });
			schema.SetRelationType("IfcRamp", new[] { "IfcRampType" });
			schema.SetRelationType("IfcRoof", new[] { "IfcRoofType" });
			schema.SetRelationType("IfcShadingDevice", new[] { "IfcShadingDeviceType" });
			schema.SetRelationType("IfcSlab", new[] { "IfcSlabType" });
			schema.SetRelationType("IfcStairFlight", new[] { "IfcStairFlightType" });
			schema.SetRelationType("IfcStair", new[] { "IfcStairType" });
			schema.SetRelationType("IfcWall", new[] { "IfcWallType" });
			schema.SetRelationType("IfcWindow", new[] { "IfcWindowType", "IfcWindowStyle" });
			schema.SetRelationType("IfcElementComponent", new[] { "IfcElementComponentType" });
			schema.SetRelationType("IfcReinforcingElement", new[] { "IfcReinforcingElementType" });
			schema.SetRelationType("IfcReinforcingBar", new[] { "IfcReinforcingBarType" });
			schema.SetRelationType("IfcReinforcingMesh", new[] { "IfcReinforcingMeshType" });
			schema.SetRelationType("IfcTendonAnchor", new[] { "IfcTendonAnchorType" });
			schema.SetRelationType("IfcTendon", new[] { "IfcTendonType" });
			schema.SetRelationType("IfcBuildingElementPart", new[] { "IfcBuildingElementPartType" });
			schema.SetRelationType("IfcDiscreteAccessory", new[] { "IfcDiscreteAccessoryType" });
			schema.SetRelationType("IfcFastener", new[] { "IfcFastenerType" });
			schema.SetRelationType("IfcMechanicalFastener", new[] { "IfcMechanicalFastenerType" });
			schema.SetRelationType("IfcVibrationIsolator", new[] { "IfcVibrationIsolatorType" });
			schema.SetRelationType("IfcFurnishingElement", new[] { "IfcFurnishingElementType" });
			schema.SetRelationType("IfcFurniture", new[] { "IfcFurnitureType" });
			schema.SetRelationType("IfcSystemFurnitureElement", new[] { "IfcSystemFurnitureElementType" });
			schema.SetRelationType("IfcDistributionElement", new[] { "IfcDistributionElementType" });
			schema.SetRelationType("IfcDistributionFlowElement", new[] { "IfcDistributionFlowElementType" });
			schema.SetRelationType("IfcDistributionChamberElement", new[] { "IfcDistributionChamberElementType" });
			schema.SetRelationType("IfcEnergyConversionDevice", new[] { "IfcEnergyConversionDeviceType" });
			schema.SetRelationType("IfcAirToAirHeatRecovery", new[] { "IfcAirToAirHeatRecoveryType" });
			schema.SetRelationType("IfcBoiler", new[] { "IfcBoilerType" });
			schema.SetRelationType("IfcBurner", new[] { "IfcBurnerType" });
			schema.SetRelationType("IfcChiller", new[] { "IfcChillerType" });
			schema.SetRelationType("IfcCoil", new[] { "IfcCoilType" });
			schema.SetRelationType("IfcCondenser", new[] { "IfcCondenserType" });
			schema.SetRelationType("IfcCooledBeam", new[] { "IfcCooledBeamType" });
			schema.SetRelationType("IfcCoolingTower", new[] { "IfcCoolingTowerType" });
			schema.SetRelationType("IfcEngine", new[] { "IfcEngineType" });
			schema.SetRelationType("IfcEvaporativeCooler", new[] { "IfcEvaporativeCoolerType" });
			schema.SetRelationType("IfcEvaporator", new[] { "IfcEvaporatorType" });
			schema.SetRelationType("IfcHeatExchanger", new[] { "IfcHeatExchangerType" });
			schema.SetRelationType("IfcHumidifier", new[] { "IfcHumidifierType" });
			schema.SetRelationType("IfcTubeBundle", new[] { "IfcTubeBundleType" });
			schema.SetRelationType("IfcUnitaryEquipment", new[] { "IfcUnitaryEquipmentType" });
			schema.SetRelationType("IfcElectricGenerator", new[] { "IfcElectricGeneratorType" });
			schema.SetRelationType("IfcElectricMotor", new[] { "IfcElectricMotorType" });
			schema.SetRelationType("IfcMotorConnection", new[] { "IfcMotorConnectionType" });
			schema.SetRelationType("IfcSolarDevice", new[] { "IfcSolarDeviceType" });
			schema.SetRelationType("IfcTransformer", new[] { "IfcTransformerType" });
			schema.SetRelationType("IfcFlowController", new[] { "IfcFlowControllerType" });
			schema.SetRelationType("IfcAirTerminalBox", new[] { "IfcAirTerminalBoxType" });
			schema.SetRelationType("IfcDamper", new[] { "IfcDamperType" });
			schema.SetRelationType("IfcFlowMeter", new[] { "IfcFlowMeterType" });
			schema.SetRelationType("IfcValve", new[] { "IfcValveType" });
			schema.SetRelationType("IfcElectricDistributionBoard", new[] { "IfcElectricDistributionBoardType" });
			schema.SetRelationType("IfcElectricTimeControl", new[] { "IfcElectricTimeControlType" });
			schema.SetRelationType("IfcProtectiveDevice", new[] { "IfcProtectiveDeviceType" });
			schema.SetRelationType("IfcSwitchingDevice", new[] { "IfcSwitchingDeviceType" });
			schema.SetRelationType("IfcFlowFitting", new[] { "IfcFlowFittingType" });
			schema.SetRelationType("IfcDuctFitting", new[] { "IfcDuctFittingType" });
			schema.SetRelationType("IfcPipeFitting", new[] { "IfcPipeFittingType" });
			schema.SetRelationType("IfcCableCarrierFitting", new[] { "IfcCableCarrierFittingType" });
			schema.SetRelationType("IfcCableFitting", new[] { "IfcCableFittingType" });
			schema.SetRelationType("IfcJunctionBox", new[] { "IfcJunctionBoxType" });
			schema.SetRelationType("IfcFlowMovingDevice", new[] { "IfcFlowMovingDeviceType" });
			schema.SetRelationType("IfcCompressor", new[] { "IfcCompressorType" });
			schema.SetRelationType("IfcFan", new[] { "IfcFanType" });
			schema.SetRelationType("IfcPump", new[] { "IfcPumpType" });
			schema.SetRelationType("IfcFlowSegment", new[] { "IfcFlowSegmentType" });
			schema.SetRelationType("IfcDuctSegment", new[] { "IfcDuctSegmentType" });
			schema.SetRelationType("IfcPipeSegment", new[] { "IfcPipeSegmentType" });
			schema.SetRelationType("IfcCableCarrierSegment", new[] { "IfcCableCarrierSegmentType" });
			schema.SetRelationType("IfcCableSegment", new[] { "IfcCableSegmentType" });
			schema.SetRelationType("IfcFlowStorageDevice", new[] { "IfcFlowStorageDeviceType" });
			schema.SetRelationType("IfcTank", new[] { "IfcTankType" });
			schema.SetRelationType("IfcElectricFlowStorageDevice", new[] { "IfcElectricFlowStorageDeviceType" });
			schema.SetRelationType("IfcFlowTerminal", new[] { "IfcFlowTerminalType" });
			schema.SetRelationType("IfcFireSuppressionTerminal", new[] { "IfcFireSuppressionTerminalType" });
			schema.SetRelationType("IfcSanitaryTerminal", new[] { "IfcSanitaryTerminalType" });
			schema.SetRelationType("IfcStackTerminal", new[] { "IfcStackTerminalType" });
			schema.SetRelationType("IfcWasteTerminal", new[] { "IfcWasteTerminalType" });
			schema.SetRelationType("IfcAirTerminal", new[] { "IfcAirTerminalType" });
			schema.SetRelationType("IfcMedicalDevice", new[] { "IfcMedicalDeviceType" });
			schema.SetRelationType("IfcSpaceHeater", new[] { "IfcSpaceHeaterType" });
			schema.SetRelationType("IfcAudioVisualAppliance", new[] { "IfcAudioVisualApplianceType" });
			schema.SetRelationType("IfcCommunicationsAppliance", new[] { "IfcCommunicationsApplianceType" });
			schema.SetRelationType("IfcElectricAppliance", new[] { "IfcElectricApplianceType" });
			schema.SetRelationType("IfcLamp", new[] { "IfcLampType" });
			schema.SetRelationType("IfcLightFixture", new[] { "IfcLightFixtureType" });
			schema.SetRelationType("IfcOutlet", new[] { "IfcOutletType" });
			schema.SetRelationType("IfcFlowTreatmentDevice", new[] { "IfcFlowTreatmentDeviceType" });
			schema.SetRelationType("IfcInterceptor", new[] { "IfcInterceptorType" });
			schema.SetRelationType("IfcDuctSilencer", new[] { "IfcDuctSilencerType" });
			schema.SetRelationType("IfcFilter", new[] { "IfcFilterType" });
			schema.SetRelationType("IfcDistributionControlElement", new[] { "IfcDistributionControlElementType" });
			schema.SetRelationType("IfcProtectiveDeviceTrippingUnit", new[] { "IfcProtectiveDeviceTrippingUnitType" });
			schema.SetRelationType("IfcActuator", new[] { "IfcActuatorType" });
			schema.SetRelationType("IfcAlarm", new[] { "IfcAlarmType" });
			schema.SetRelationType("IfcController", new[] { "IfcControllerType" });
			schema.SetRelationType("IfcFlowInstrument", new[] { "IfcFlowInstrumentType" });
			schema.SetRelationType("IfcSensor", new[] { "IfcSensorType" });
			schema.SetRelationType("IfcUnitaryControlElement", new[] { "IfcUnitaryControlElementType" });
			schema.SetRelationType("IfcCivilElement", new[] { "IfcCivilElementType" });
			schema.SetRelationType("IfcElementAssembly", new[] { "IfcElementAssemblyType" });
			schema.SetRelationType("IfcGeographicElement", new[] { "IfcGeographicElementType" });
			schema.SetRelationType("IfcTransportElement", new[] { "IfcTransportElementType" });
			schema.SetRelationType("IfcSpatialElement", new[] { "IfcSpatialElementType" });
			schema.SetRelationType("IfcSpatialStructureElement", new[] { "IfcSpatialStructureElementType" });
			schema.SetRelationType("IfcSpace", new[] { "IfcSpaceType" });
			schema.SetRelationType("IfcSpatialZone", new[] { "IfcSpatialZoneType" });
			schema.SetRelationType("IfcTypeProcess", new[] { "IfcTypeProcess" });
			schema.SetRelationType("IfcEvent", new[] { "IfcEventType" });
			schema.SetRelationType("IfcProcedure", new[] { "IfcProcedureType" });
			schema.SetRelationType("IfcTask", new[] { "IfcTaskType" });
			schema.SetRelationType("IfcTypeResource", new[] { "IfcTypeResource" });
			schema.SetRelationType("IfcConstructionResource", new[] { "IfcConstructionResourceType" });
			schema.SetRelationType("IfcConstructionEquipmentResource", new[] { "IfcConstructionEquipmentResourceType" });
			schema.SetRelationType("IfcConstructionMaterialResource", new[] { "IfcConstructionMaterialResourceType" });
			schema.SetRelationType("IfcConstructionProductResource", new[] { "IfcConstructionProductResourceType" });
			schema.SetRelationType("IfcCrewResource", new[] { "IfcCrewResourceType" });
			schema.SetRelationType("IfcLaborResource", new[] { "IfcLaborResourceType" });
			schema.SetRelationType("IfcSubContractResource", new[] { "IfcSubContractResourceType" });
		}
	}
}
