// generated running xbim.xids.generator
using System;
using System.Collections.Generic;
using System.Text;

namespace Xbim.InformationSpecifications.Helpers
{
    public enum IfcMeasures
    {
		String,
		Number,
		AmountOfSubstance,
		AreaDensity,
		Area,
		DynamicViscosity,
		ElectricCapacitance,
		ElectricCharge,
		ElectricConductance,
		ElectricCurrent,
		ElectricResistance,
		ElectricVoltage,
		Energy,
		Force,
		Frequency,
		HeatFluxDensity,
		Heating,
		Illuminance,
		IonConcentration,
		IsoThermalMoistureCapacity,
		Length,
		Speed,
		LuminousFlux,
		LuminousIntensity,
		MassDensity,
		MassFlowRate,
		Mass,
		MassPerLength,
		ModulusOfElasticity,
		MoistureDiffusivity,
		MolecularWeight,
		MomentOfInertia,
		PH,
		PlanarForce,
		Angle,
		PlaneAngle,
		Power,
		Pressure,
		RadioActivity,
		Ratio,
		RotationalFrequency,
		SectionModulus,
		SoundPower,
		SoundPressure,
		SpecificHeatCapacity,
		TemperatureRateOfChange,
		ThermalConductivity,
		Temperature,
		Time,
		Torque,
		VaporPermeability,
		Volume,
		VolumetricFlowRate,
    }
}
