// Enums.generated.cs is automatically generated by xbim.xids.generator.Execute_GenerateIfcMeasureDictionary() using Xbim.Essentials 6.0.445.0
using System;
using System.Collections.Generic;
using System.Text;

namespace Xbim.InformationSpecifications.Helpers
{
    /// <summary>
    /// Determines data type constraints and conversion for measures.
    /// </summary>
    [Obsolete("Should use the IdsLib.IfcSchema.SchemaInfo.IfcMeasureInformation instead.")]
    public enum IfcValue
    {
		/// Absorbed radioactivity dose, expressed in gray
		IFCABSORBEDDOSEMEASURE,
		/// Acceleration, expressed in m / s2
		IFCACCELERATIONMEASURE,
		/// Amount of substance, expressed in mole
		IFCAMOUNTOFSUBSTANCEMEASURE,
		/// Angular velocity, expressed in 1 / s
		IFCANGULARVELOCITYMEASURE,
		/// Area density, expressed in kg / m2
		IFCAREADENSITYMEASURE,
		/// Area, expressed in square meter
		IFCAREAMEASURE,
		/// Curvature, expressed in 1 / m
		IFCCURVATUREMEASURE,
		/// Dose equivalent, expressed in sievert
		IFCDOSEEQUIVALENTMEASURE,
		/// Dynamic viscosity, expressed in kg / m s
		IFCDYNAMICVISCOSITYMEASURE,
		/// Electric capacitance, expressed in farad
		IFCELECTRICCAPACITANCEMEASURE,
		/// Electric charge, expressed in coulomb
		IFCELECTRICCHARGEMEASURE,
		/// Electric conductance, expressed in siemens
		IFCELECTRICCONDUCTANCEMEASURE,
		/// Electric current, expressed in ampere
		IFCELECTRICCURRENTMEASURE,
		/// Electric resistance, expressed in ohm
		IFCELECTRICRESISTANCEMEASURE,
		/// Electric voltage, expressed in volt
		IFCELECTRICVOLTAGEMEASURE,
		/// Energy, expressed in joule
		IFCENERGYMEASURE,
		/// Force, expressed in newton
		IFCFORCEMEASURE,
		/// Frequency, expressed in hertz
		IFCFREQUENCYMEASURE,
		/// Heat flux density, expressed in kg / s3
		IFCHEATFLUXDENSITYMEASURE,
		/// Heating, expressed in m2 kg / s2 K
		IFCHEATINGVALUEMEASURE,
		/// Illuminance, expressed in lux
		IFCILLUMINANCEMEASURE,
		/// Inductance, expressed in henry
		IFCINDUCTANCEMEASURE,
		/// Count rate, expressed in 1 / s
		IFCINTEGERCOUNTRATEMEASURE,
		/// Ion concentration measure, expressed in kg / m3
		IFCIONCONCENTRATIONMEASURE,
		/// Iso thermal moisture capacity, expressed in m3 / kg
		IFCISOTHERMALMOISTURECAPACITYMEASURE,
		/// Kinematic viscosity, expressed in m2 / s
		IFCKINEMATICVISCOSITYMEASURE,
		/// Length, expressed in meter
		IFCLENGTHMEASURE,
		/// Linear force, expressed in kg / s2
		IFCLINEARFORCEMEASURE,
		/// Linear moment, expressed in m kg / s2
		IFCLINEARMOMENTMEASURE,
		/// Linear stiffness, expressed in kg / s2
		IFCLINEARSTIFFNESSMEASURE,
		/// Speed, expressed in m / s
		IFCLINEARVELOCITYMEASURE,
		/// Luminous flux, expressed in lumen
		IFCLUMINOUSFLUXMEASURE,
		/// Luminous intensity distribution, expressed in 1
		IFCLUMINOUSINTENSITYDISTRIBUTIONMEASURE,
		/// Luminous intensity, expressed in candela
		IFCLUMINOUSINTENSITYMEASURE,
		/// Magnetic flux density, expressed in tesla
		IFCMAGNETICFLUXDENSITYMEASURE,
		/// Magnetic flux, expressed in weber
		IFCMAGNETICFLUXMEASURE,
		/// Mass density, expressed in kg / m3
		IFCMASSDENSITYMEASURE,
		/// Mass flow rate, expressed in kg / s
		IFCMASSFLOWRATEMEASURE,
		/// Mass, expressed in kilogram
		IFCMASSMEASURE,
		/// Mass per length, expressed in kg / m
		IFCMASSPERLENGTHMEASURE,
		/// Modulus of elasticity, expressed in kg / m s2
		IFCMODULUSOFELASTICITYMEASURE,
		/// Modulus of linear subgrade reaction, expressed in kg / m s2
		IFCMODULUSOFLINEARSUBGRADEREACTIONMEASURE,
		/// Modulus of rotational subgrade reaction, expressed in m kg / s2
		IFCMODULUSOFROTATIONALSUBGRADEREACTIONMEASURE,
		/// Modulus of subgrade reaction, expressed in kg / m2 s2
		IFCMODULUSOFSUBGRADEREACTIONMEASURE,
		/// Moisture diffusivity, expressed in m3 / s
		IFCMOISTUREDIFFUSIVITYMEASURE,
		/// Molecular weight, expressed in kg / mol
		IFCMOLECULARWEIGHTMEASURE,
		/// Moment of inertia, expressed in m4
		IFCMOMENTOFINERTIAMEASURE,
		/// Non negative length, expressed in meter
		IFCNONNEGATIVELENGTHMEASURE,
		/// pH, expressed in 1
		IFCPHMEASURE,
		/// Planar force, expressed in pascal
		IFCPLANARFORCEMEASURE,
		/// Angle, expressed in radian
		IFCPLANEANGLEMEASURE,
		/// Positive length, expressed in meter
		IFCPOSITIVELENGTHMEASURE,
		/// Positive plane angle, expressed in radian
		IFCPOSITIVEPLANEANGLEMEASURE,
		/// Power, expressed in watt
		IFCPOWERMEASURE,
		/// Pressure, expressed in pascal
		IFCPRESSUREMEASURE,
		/// Radio activity, expressed in becquerel
		IFCRADIOACTIVITYMEASURE,
		/// Rotational frequency, expressed in hertz
		IFCROTATIONALFREQUENCYMEASURE,
		/// Rotational mass, expressed in m2 kg
		IFCROTATIONALMASSMEASURE,
		/// Rotational stiffness, expressed in m2 kg / s2
		IFCROTATIONALSTIFFNESSMEASURE,
		/// Sectional area integral, expressed in m5
		IFCSECTIONALAREAINTEGRALMEASURE,
		/// Section modulus, expressed in m3
		IFCSECTIONMODULUSMEASURE,
		/// Shear modulus, expressed in kg / m s2
		IFCSHEARMODULUSMEASURE,
		/// Solid angle, expressed in steradian
		IFCSOLIDANGLEMEASURE,
		/// Sound power level, expressed in decibel
		IFCSOUNDPOWERLEVELMEASURE,
		/// Sound power, expressed in decibel
		IFCSOUNDPOWERMEASURE,
		/// Sound pressure level, expressed in decibel
		IFCSOUNDPRESSURELEVELMEASURE,
		/// Sound pressure, expressed in decibel
		IFCSOUNDPRESSUREMEASURE,
		/// Specific heat capacity, expressed in m2 / s2 K
		IFCSPECIFICHEATCAPACITYMEASURE,
		/// Temperature gradient, expressed in K / m
		IFCTEMPERATUREGRADIENTMEASURE,
		/// Temperature rate of change, expressed in K / s
		IFCTEMPERATURERATEOFCHANGEMEASURE,
		/// Thermal admittance, expressed in kg / s3 K
		IFCTHERMALADMITTANCEMEASURE,
		/// Thermal conductivity, expressed in m kg / s3 K
		IFCTHERMALCONDUCTIVITYMEASURE,
		/// Thermal expansion coefficient, expressed in 1 / K
		IFCTHERMALEXPANSIONCOEFFICIENTMEASURE,
		/// Thermal resistance, expressed in s3 K / kg
		IFCTHERMALRESISTANCEMEASURE,
		/// Thermal transmittance, expressed in kg / s3 K
		IFCTHERMALTRANSMITTANCEMEASURE,
		/// Temperature, expressed in kelvin
		IFCTHERMODYNAMICTEMPERATUREMEASURE,
		/// Time, expressed in second
		IFCTIMEMEASURE,
		/// Torque, expressed in m2 kg / s2
		IFCTORQUEMEASURE,
		/// Vapor permeability, expressed in s
		IFCVAPORPERMEABILITYMEASURE,
		/// Volume, expressed in cubic meter
		IFCVOLUMEMEASURE,
		/// Volumetric flow rate, expressed in m3 / s
		IFCVOLUMETRICFLOWRATEMEASURE,
		/// Warping constant, expressed in m6
		IFCWARPINGCONSTANTMEASURE,
		/// Warping moment, expressed in m3 kg / s2
		IFCWARPINGMOMENTMEASURE,
		/// A string,
		IfcText,
		/// An identifier expressed as string,
		IfcIdentifier,

    }
}
